@startuml

actor Пользователь
actor Администратор


rectangle Умный_дом {
  Пользователь -> (ААА)
  Администратор -> (ААА)
  Администратор -> (Управление типами пользователей)
  Администратор -> (Управление типами модулей)
  Администратор -> (Управление типами событий в логах)
  Пользователь ---> (Управление домами)
  (Управление домами)-> (Добавление дома)
  (Управление домами)-> (Удаление дома)
  (Управление домами) -> (Управление локациями)
  (Управление локациями)-> (Добавление локаций)
  (Управление локациями)-> (Удаление локаций)
  Пользователь -> (Управление модулями)
  (Управление модулями)-> (Добавление модулей)
  (Управление модулями)-> (Удаление модулей)
  (Управление модулями)-> (Привязать модуль к локации)
  (Управление модулями)-> (Отвязать модуль от локации) 
  (Управление модулями)-> (Установить знаечние модуля) 
  Пользователь -> (Мониторинг модулей)
  Администратор -> (Мониторинг модулей)
  (Мониторинг модулей)-> (Отображение показателей и состояния модулей)
  (Мониторинг модулей)-> (Отображение доступности модулей)
  (Мониторинг модулей)-> (Отображение событий модуля из логов)
}
@enduml
